# Generated by Django 4.1.7 on 2023-02-23 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workoutlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('bodypart', models.CharField(blank=True, choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Leg', 'Leg'), ('Core', 'Core'), ('Shoulder', 'shoulder')], max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Targetshoulderworkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('workout1', models.CharField(blank=True, choices=[('Frontrisese', 'Frontrisese'), ('Siderises', 'Siderises'), ('Facepull', 'Facepull'), ('Shugs', 'Shugs')], max_length=200, null=True)),
                ('workout2', models.CharField(blank=True, choices=[('Frontrisese', 'Frontrisese'), ('Siderises', 'Siderises'), ('Facepull', 'Facepull'), ('Shugs', 'Shugs')], max_length=200, null=True)),
                ('workout3', models.CharField(blank=True, choices=[('Frontrisese', 'Frontrisese'), ('Siderises', 'Siderises'), ('Facepull', 'Facepull'), ('Shugs', 'Shugs')], max_length=200, null=True)),
                ('workout4', models.CharField(blank=True, choices=[('Frontrisese', 'Frontrisese'), ('Siderises', 'Siderises'), ('Facepull', 'Facepull'), ('Shugs', 'Shugs')], max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Targetlegworkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('workout1', models.CharField(blank=True, choices=[('Squats', 'Squats'), ('Lunge', 'Lunge'), ('RDL', 'RDL'), ('Legpress', 'Legpress')], max_length=200, null=True)),
                ('workout2', models.CharField(blank=True, choices=[('Squats', 'Squats'), ('Lunge', 'Lunge'), ('RDL', 'RDL'), ('Legpress', 'Legpress')], max_length=200, null=True)),
                ('workout3', models.CharField(blank=True, choices=[('Squats', 'Squats'), ('Lunge', 'Lunge'), ('RDL', 'RDL'), ('Legpress', 'Legpress')], max_length=200, null=True)),
                ('workout4', models.CharField(blank=True, choices=[('Squats', 'Squats'), ('Lunge', 'Lunge'), ('RDL', 'RDL'), ('Legpress', 'Legpress')], max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Targetcoreworkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('workout1', models.CharField(blank=True, choices=[('cablecrunch', 'cablecrunch'), ('Babyshark', 'Babyshark'), ('hanginglegraise', 'hanginglegraise'), ('plank', 'plank')], max_length=200, null=True)),
                ('workout2', models.CharField(blank=True, choices=[('cablecrunch', 'cablecrunch'), ('Babyshark', 'Babyshark'), ('hanginglegraise', 'hanginglegraise'), ('plank', 'plank')], max_length=200, null=True)),
                ('workout3', models.CharField(blank=True, choices=[('cablecrunch', 'cablecrunch'), ('Babyshark', 'Babyshark'), ('hanginglegraise', 'hanginglegraise'), ('plank', 'plank')], max_length=200, null=True)),
                ('workout4', models.CharField(blank=True, choices=[('cablecrunch', 'cablecrunch'), ('Babyshark', 'Babyshark'), ('hanginglegraise', 'hanginglegraise'), ('plank', 'plank')], max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Targetchestworkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('workout1', models.CharField(blank=True, choices=[('Flatpress', 'Flatpress'), ('Inclintpress', 'Inclintpress'), ('Declientpress', 'Declientpress'), ('cableflys', 'cableflys')], max_length=200, null=True)),
                ('workout2', models.CharField(blank=True, choices=[('Flatpress', 'Flatpress'), ('Inclintpress', 'Inclintpress'), ('Declientpress', 'Declientpress'), ('cableflys', 'cableflys')], max_length=200, null=True)),
                ('workout3', models.CharField(blank=True, choices=[('Flatpress', 'Flatpress'), ('Inclintpress', 'Inclintpress'), ('Declientpress', 'Declientpress'), ('cableflys', 'cableflys')], max_length=200, null=True)),
                ('workout4', models.CharField(blank=True, choices=[('Flatpress', 'Flatpress'), ('Inclintpress', 'Inclintpress'), ('Declientpress', 'Declientpress'), ('cableflys', 'cableflys')], max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Targetbackworkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('workout1', models.CharField(blank=True, choices=[('Pullups', 'Pullups'), ('Bendoverrows', 'Bendoverrows'), ('Shugs', 'Shugs'), ('Dublerows', 'Dublerows')], max_length=200, null=True)),
                ('workout2', models.CharField(blank=True, choices=[('Pullups', 'Pullups'), ('Bendoverrows', 'Bendoverrows'), ('Shugs', 'Shugs'), ('Dublerows', 'Dublerows')], max_length=200, null=True)),
                ('workout3', models.CharField(blank=True, choices=[('Pullups', 'Pullups'), ('Bendoverrows', 'Bendoverrows'), ('Shugs', 'Shugs'), ('Dublerows', 'Dublerows')], max_length=200, null=True)),
                ('workout4', models.CharField(blank=True, choices=[('Pullups', 'Pullups'), ('Bendoverrows', 'Bendoverrows'), ('Shugs', 'Shugs'), ('Dublerows', 'Dublerows')], max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shoulderlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('exercises', models.CharField(max_length=200, null=True)),
                ('set1', models.IntegerField(blank=True, null=True)),
                ('set2', models.IntegerField(blank=True, null=True)),
                ('set3', models.IntegerField(blank=True, null=True)),
                ('set4', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Exercisesroutine.workoutlog')),
            ],
        ),
        migrations.CreateModel(
            name='Leglog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('exercises', models.CharField(max_length=200, null=True)),
                ('set1', models.IntegerField(blank=True, null=True)),
                ('set2', models.IntegerField(blank=True, null=True)),
                ('set3', models.IntegerField(blank=True, null=True)),
                ('set4', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Exercisesroutine.workoutlog')),
            ],
        ),
        migrations.CreateModel(
            name='Corelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('exercises', models.CharField(max_length=200, null=True)),
                ('set1', models.IntegerField(blank=True, null=True)),
                ('set2', models.IntegerField(blank=True, null=True)),
                ('set3', models.IntegerField(blank=True, null=True)),
                ('set4', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Exercisesroutine.workoutlog')),
            ],
        ),
        migrations.CreateModel(
            name='Chestlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('exercises', models.CharField(max_length=200, null=True)),
                ('set1', models.IntegerField(blank=True, null=True)),
                ('set2', models.IntegerField(blank=True, null=True)),
                ('set3', models.IntegerField(blank=True, null=True)),
                ('set4', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Exercisesroutine.workoutlog')),
            ],
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('exercises', models.CharField(max_length=200, null=True)),
                ('set1', models.IntegerField(blank=True, null=True)),
                ('set2', models.IntegerField(blank=True, null=True)),
                ('set3', models.IntegerField(blank=True, null=True)),
                ('set4', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Exercisesroutine.workoutlog')),
            ],
        ),
    ]
