# Generated by Django 4.1.7 on 2023-02-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercisesroutine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='set1_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backlog',
            name='set2_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backlog',
            name='set3_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backlog',
            name='set4_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chestlog',
            name='set1_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chestlog',
            name='set2_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chestlog',
            name='set3_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chestlog',
            name='set4_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corelog',
            name='set1_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corelog',
            name='set2_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corelog',
            name='set3_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corelog',
            name='set4_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leglog',
            name='set1_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leglog',
            name='set2_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leglog',
            name='set3_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leglog',
            name='set4_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoulderlog',
            name='set1_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoulderlog',
            name='set2_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoulderlog',
            name='set3_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoulderlog',
            name='set4_weight_inkg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
