# Generated by Django 4.1.7 on 2023-03-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercisesroutine', '0003_remove_chestlog_workout_remove_corelog_workout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutlog',
            old_name='bodypary',
            new_name='bodypart',
        ),
    ]
