# Generated by Django 4.1.7 on 2023-02-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodroutine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlog',
            name='lunchfastcalories',
        ),
        migrations.RemoveField(
            model_name='targetfoodroutine',
            name='lunchfastcalories',
        ),
        migrations.AddField(
            model_name='foodlog',
            name='lunchcalories',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='targetfoodroutine',
            name='lunchcalories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='breakfastcalories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='dinnercalories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='snackscalories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='breakfastcalories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='dinnercalories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='snackscalories',
            field=models.IntegerField(null=True),
        ),
    ]
