# Generated by Django 4.1.7 on 2023-02-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodroutine', '0002_remove_foodlog_lunchfastcalories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='breakfast',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='dinner',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='lunch',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='snacks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='breakfast',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='dinner',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='lunch',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='snacks',
            field=models.TextField(null=True),
        ),
    ]
