# Generated by Django 4.1.7 on 2023-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodroutine', '0004_breakfastlog_dinnerlog_lunchlog_snackslog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='breakfast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='breakfastcalories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='dinner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='dinnercalories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='lunch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='lunchcalories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='snacks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='snackscalories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
