# Generated by Django 4.1.7 on 2023-02-22 12:20

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodroutine', '0005_alter_targetfoodroutine_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetfoodroutine',
            name='Testing',
            field=djrichtextfield.models.RichTextField(null=True),
        ),
    ]
