# Generated by Django 4.1.7 on 2023-02-22 12:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodroutine', '0006_targetfoodroutine_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetfoodroutine',
            name='Testing',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
