# Generated by Django 4.1.7 on 2023-02-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodroutine', '0008_remove_targetfoodroutine_testing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfastlog',
            name='breakfast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breakfastlog',
            name='breakfastcalories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerlog',
            name='dinner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerlog',
            name='dinnercalories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lunchlog',
            name='lunch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lunchlog',
            name='lunchcalories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snackslog',
            name='snacks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snackslog',
            name='snackscalories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
